# Generated by Django 3.0.8 on 2020-07-18 22:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_selling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='request_date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='tel_number',
            field=models.CharField(max_length=11),
        ),
    ]
