# Generated by Django 3.0.8 on 2020-07-19 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book_selling', '0002_auto_20200718_2207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='books',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book', to='book_selling.Book', verbose_name='Книга'),
        ),
    ]
